openapi: 3.0.0
info:
  title: test.v3
  version: '3.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /others:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-others
components:
  schemas: {}
