openapi: 3.0.0
info:
  title: test.v4
  version: '4.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /somapathj:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-somapathj
components:
  schemas: {}
