openapi: 3.0.0
info:
  title: test
  version: v2
  description: ''
servers:
  - url: 'http://localhost:3001'
paths:
  /tests:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-tests
components:
  schemas: {}
