openapi: 3.0.0
info:
  title: test.v3
  version: v3
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /others:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-others
components:
  schemas: {}
